# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: pygments

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            'About Linux'
tagline:          'Linux fances'
description:      'Learn anything about Linux'
url:              'http://blogeri.fs.al'
baseurl:          'http://localhost:4000'

# Navigation
navigation:
- text: About
  url: /about/
- text: Blog
  url: /blog/
- text: Archive
  url : /archive/
- text: Tags
  url: /tags/
- text:Geri
  url:
# Author Details
author:         'Geri Gjylbegu'
#linkedin:       'https://ae.linkedin.com/in/olakara/'
#twitter:        'https://twitter.com/olakara'
#facebook:       'https://www.facebook.com/olakara'
#gplus:          'https://plus.google.com/100425464897246255887/'

# Google Analytics
gahandler: 'UA-52149651-1'

# Disqus
disqushandler: 'blogerifsal'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.7.9
